version: '3.5'

networks:
  web-app-net:
    name: my-web-app-net
    #driver: overlay
    driver: bridge

services:
  exporter:
    image: prom/node-exporter:latest
    ports:
      - 9100
    networks:
      - web-app-net

  prom:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yaml
    depends_on:
      - exporter
    networks:
      - web-app-net
      
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prom
    networks:
      - web-app-net
#end of scripts