version: '3.5'

networks:
  web-app-net:
    name: my-web-app-net
    #driver: overlay
    driver: bridge

services: 
  user-profile:
    image: engrajibkumerghosh/ms-training-repo-v1:user-profile-v1.0.18
    environment:
      management.endpoints.web.exposure.include: health,metrics,httptrace,prometheus
      app.eureka.service.host: eureka-service-discovery
      app.eureka.service.port: 801
      app.db.host: pg-userProfileDB
      app.db.port: 5433
      app.db.name: userProfileDB
      app.db.username: root
      app.db.password: root@123
      app.zookeeper.host: zookeeper
      app.zookeeper.port: 2181
      app.kafka.host: kafka
      app.kafka.port: 9092
    ports:
      - 8084:8084
    extra_hosts:
      - "stg-sso.dit.gov.bt:172.30.78.24"
      - "staging-datahub-apim.dit.gov.bt:172.30.78.130"
      - "eureka-service-discovery:172.30.3.4"
      - "pg-userProfileDB:172.30.3.20"
      - "zookeeper:172.30.3.18"
      - "kafka:172.30.3.18"
      - "6441d0d9fe09:172.30.3.6"
      - "07f7f3bdc2c6:172.30.3.6"
      - "e89c8ca855ae:172.30.3.7"
      - "2cbdcc2d566d:172.30.3.7"
    restart: on-failure
    networks:
      - web-app-net
      
#end of scripts