version: '3.5'

networks:
  web-app-net:
    name: my-web-app-net
    #driver: overlay
    driver: bridge

volumes:
  redis-inmemory-storage:
  activemq-storage:
  pg-enrolmentDB-storage:
  pg-medicalDB-storage:
  pg-notifyDB-storage:

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - web-app-net
    volumes:
      - redis-inmemory-storage:/data

  activemq:
    image: webcenter/activemq
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
    environment:
      - ACTIVEMQ_MIN_MEMORY=512
      - ACTIVEMQ_MAX_MEMORY=2048
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
    restart: on-failure
    networks:
      - web-app-net
    volumes:
      - activemq-storage:/var/log/activemq

  fake-smtp:
    image: rnwood/smtp4dev
    ports:
      - 587:25
      - 3000:80
    networks:
      - web-app-net

  pg-enrolmentDB:
    image: postgres
    environment:
      POSTGRES_DB: enrolmentDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root@123
    ports:
      - 5435:5432
    networks:
      - web-app-net
    volumes:
      - pg-enrolmentDB-storage:/var/lib/postgresql/data

  pg-medicalDB:
    image: postgres
    environment:
      POSTGRES_DB: medicalDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root@123
    ports:
      - 5436:5432
    networks:
      - web-app-net
    volumes:
      - pg-medicalDB-storage:/var/lib/postgresql/data

  pg-notifyDB:
    image: postgres
    environment:
      POSTGRES_DB: notifyDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root@123
    ports:
      - 5437:5432
    networks:
      - web-app-net
    volumes:
      - pg-notifyDB-storage:/var/lib/postgresql/data

  api-gateway:
    image: engrajibkumerghosh/ms-training-repo-v1:cloud-gateway-service-v1.0
    environment:
      management.endpoints.web.exposure.include: health,metrics,httptrace,prometheus,gateway
      app.eureka.service.host: eureka-service-discovery
      app.eureka.service.port: 801
      redis.host: redis
      redis.port: 6379
    ports:
      - 80:80
    depends_on:
      - eureka-service-discovery
      - auth-service
      - first-service
      - second-service
      - user-profile
      - training-management
      - enrolment-deferment-exemption
      - medical-screening
      - notification
    restart: on-failure
    networks:
      - web-app-net

  auth-service:
    image: engrajibkumerghosh/ms-training-repo-v1:auth-service-v1.0
    environment:
      management.endpoints.web.exposure.include: health,metrics,httptrace,prometheus
      app.eureka.service.host: eureka-service-discovery
      app.eureka.service.port: 801
      app.redis.host: redis
      app.redis.port: 6379
      app.mail.host: 172.30.3.140
      app.mail.port: 587
      app.activemq.host: activemq
      app.activemq.port: 61616
      app.db.host: pg-authDB
      app.db.port: 5432
    ports:
      - 8093:8083
    depends_on:
      - eureka-service-discovery
    restart: on-failure
    networks:
      - web-app-net

  second-service:
    image: engrajibkumerghosh/ms-training-repo-v1:second-service-v1.0
    environment:
      management.endpoints.web.exposure.include: health,metrics,httptrace,prometheus
      app.eureka.service.host: eureka-service-discovery
      app.eureka.service.port: 801
    ports:
      - 8082:8082
    depends_on:
      - eureka-service-discovery
    restart: on-failure
    networks:
      - web-app-net

  user-profile:
    image: engrajibkumerghosh/ms-training-repo-v1:user-profile-v1.0
    environment:
      management.endpoints.web.exposure.include: health,metrics,httptrace,prometheus
      app.eureka.service.host: eureka-service-discovery
      app.eureka.service.port: 801
    ports:
      - 8094:8084
    depends_on:
      - eureka-service-discovery
    restart: on-failure
    networks:
      - web-app-net

  enrolment-deferment-exemption:
    image: engrajibkumerghosh/ms-training-repo-v1:enrolment-deferment-exemption-v1.0
    environment:
      management.endpoints.web.exposure.include: health,metrics,httptrace,prometheus
      app.eureka.service.host: eureka-service-discovery
      app.eureka.service.port: 801
    ports:
      - 8097:8087
    depends_on:
      - eureka-service-discovery
    restart: on-failure
    networks:
      - web-app-net

  medical-screening:
    image: engrajibkumerghosh/ms-training-repo-v1:medical-screening-v1.0
    environment:
      management.endpoints.web.exposure.include: health,metrics,httptrace,prometheus
      app.eureka.service.host: eureka-service-discovery
      app.eureka.service.port: 801
    ports:
      - 8088:8088
    depends_on:
      - eureka-service-discovery
    restart: on-failure
    networks:
      - web-app-net

  notification:
    image: engrajibkumerghosh/ms-training-repo-v1:notification-v1.0
    environment:
      management.endpoints.web.exposure.include: health,metrics,httptrace,prometheus
      app.eureka.service.host: eureka-service-discovery
      app.eureka.service.port: 801
    ports:
      - 8085:8085
    depends_on:
      - eureka-service-discovery
    restart: on-failure
    networks:
      - web-app-net

#end of scripts