version: '3.5'

networks:
  web-app-net:
    name: my-web-app-net
    #driver: overlay
    driver: bridge

services:  
  nginx:
    image: nginx/nginx-exporter:latest
    environment:
      management.endpoints.web.exposure.include: health,metrics,httptrace,prometheus
    ports:
      - 8443:8443
    restart: on-failure
    networks:
      - web-app-net
      
#end of scripts