version: '3.5'

networks:
  web-app-net:
    name: my-web-app-net
    #driver: overlay
    driver: bridge

volumes:
  pg-enrolmentDB-storage:
  pgadmin-enrolmentDB-data:

services:
  pg-enrolmentDB:
    image: postgres
    environment:
      POSTGRES_DB: enrolmentDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root@123
    ports:
      - 5432:5432
    networks:
      - web-app-net
    volumes:
      - pg-enrolmentDB-storage:/var/lib/postgresql/data

  pgadmin-enrolmentDB:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@mypage.com
      PGADMIN_DEFAULT_PASSWORD: root@123
    volumes:
      - pgadmin-enrolmentDB-data:/var/lib/pgadmin
    restart: on-failure
    networks:
      - web-app-net
    depends_on:
      - pg-enrolmentDB

  enrolment-deferment-exemption-webapp:
    image: enrolment-deferment-exemption-web-service:1.0
    build:
      context: .
      dockerfile: ./enrolment-deferment-exemption/Dockerfile
    environment:
      management.endpoints.web.exposure.include: health,metrics,httptrace,prometheus
      app.eureka.service.host: ${app.eureka.service.host}
      app.eureka.service.port: ${app.eureka.service.port}
    ports:
      - 8067:8087
    restart: on-failure
    networks:
      - web-app-net

  medical-screening-webapp:
    image: medical-screening-web-service:1.0
    build:
      context: .
      dockerfile: ./medical-screening/Dockerfile
    environment:
      management.endpoints.web.exposure.include: health,metrics,httptrace,prometheus
      app.eureka.service.host: ${app.eureka.service.host}
      app.eureka.service.port: ${app.eureka.service.port}
    ports:
      - 8068:8088
    restart: on-failure
    networks:
      - web-app-net

  notification-webapp:
    image: notification-web-service:1.0
    build:
      context: .
      dockerfile: ./notification/Dockerfile
    environment:
      management.endpoints.web.exposure.include: health,metrics,httptrace,prometheus
      app.eureka.service.host: ${app.eureka.service.host}
      app.eureka.service.port: ${app.eureka.service.port}
    ports:
      - 8065:8085
    restart: on-failure
    networks:
      - web-app-net

#end of scripts