version: '3.5'

networks:
  web-app-net:
    name: my-web-app-net
    #driver: overlay
    driver: bridge

volumes:
  pg-userProfileDB-storage:
  pg-medicalDB-storage:

services:
  pg-userProfileDB:
    image: postgres
    environment:
      POSTGRES_DB: userProfileDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root@123
    ports:
      - 5433:5432
    networks:
      - web-app-net
    volumes:
      - pg-userProfileDB-storage:/var/lib/postgresql/data
      
  pg-medicalDB:
    image: postgres
    environment:
      POSTGRES_DB: medicalDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root@123
    ports:
      - 5436:5432
    networks:
      - web-app-net
    volumes:
      - pg-medicalDB-storage:/var/lib/postgresql/data  

#end of scripts