version: '3.5'

networks:
  web-app-net:
    name: my-web-app-net
    #driver: overlay
    driver: bridge

services:  
  auth-service:
    image: engrajibkumerghosh/ms-training-repo-v1:auth-service-v1.0.18
    environment:
      management.endpoints.web.exposure.include: health,metrics,httptrace,prometheus
      app.eureka.service.host: eureka-service-discovery
      app.eureka.service.port: 801
      app.redis.host: redis
      app.redis.port: 6379
      app.redis.password: gyalsung@2023
      app.mail.host: 172.30.3.18
      app.mail.port: 587
      app.activemq.host: activemq
      app.activemq.port: 61616
      app.db.host: pg-authDB
      app.db.port: 5432
      app.db.name: authDB
      app.db.username: root
      app.db.password: root@123
      app.zookeeper.host: zookeeper
      app.zookeeper.port: 2181
      app.kafka.host: kafka
      app.kafka.port: 9092
    ports:
      - 8083:8083
    extra_hosts:
      - "eureka-service-discovery:172.30.3.4"
      - "redis:172.30.3.18"
      - "activemq:172.30.3.18"
      - "pg-authDB:172.30.3.19"
      - "zookeeper:172.30.3.18"
      - "kafka:172.30.3.18"
    restart: on-failure
    networks:
      - web-app-net 
      
  training-management:
    image: engrajibkumerghosh/ms-training-repo-v1:training-management-v1.0.18
    environment:
      management.endpoints.web.exposure.include: health,metrics,httptrace,prometheus
      app.eureka.service.host: eureka-service-discovery
      app.eureka.service.port: 801
      app.db.host: pg-trainingDB
      app.db.port: 5434
      app.db.name: trainingDB
      app.db.username: root
      app.db.password: root@123
      app.zookeeper.host: zookeeper
      app.zookeeper.port: 2181
      app.kafka.host: kafka
      app.kafka.port: 9092
    ports:
      - 8086:8086
    extra_hosts:
      - "eureka-service-discovery:172.30.3.4"
      - "pg-trainingDB:172.30.3.22"
      - "zookeeper:172.30.3.18"
      - "kafka:172.30.3.18"
    restart: on-failure
    networks:
      - web-app-net  

#end of scripts