version: '3.5'

networks:
  web-app-net:
    name: my-web-app-net
    #driver: overlay
    driver: bridge

services:
  nginx:
    container_name: nginx-ha-nlb
    image: nginx:latest
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: on-failure
    networks:
      - web-app-net
      
#end of scripts