version: '3.5'

networks:
  web-app-net:
    name: my-web-app-net
    #driver: overlay
    driver: bridge

services:
  discovery-service:
    image: discovery-service:1.0
    build:
      context: .
      dockerfile: ./eureka-service-discovery/Dockerfile
    environment:
      management.endpoints.web.exposure.include: health,metrics,httptrace,prometheus
    ports:
      - 801:801
    restart: on-failure
    networks:
      - web-app-net

#end of scripts