spring:
  application:
    name: training-management
  main:
    banner-mode: "off"
server:
  port: 8086
  servlet:
    context-path: /api/training/management
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,httptrace,prometheus
app:
  home:
    #logs: /Users/${USER}/Logs
    logs: /Users/Logs
#Eureka-Config:
app.eureka.service.host: localhost
app.eureka.service.port: 801
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka.service.host}:${app.eureka.service.port}/eureka
#    registerWithEureka: true
#    fetchRegistry: true
#  instance:
#    preferIpAddress: true