spring:
  application:
    name: notification
  main:
    banner-mode: "off"
    allow-circular-references: true
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: "none"
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "dhi.bhutan.bt@gmail.com"
    password: "czconvqzibicectb"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
bezkoder:
  app:
    jwtSecret: "bezKoderSecretKey"
    jwtExpirationMs: 86400000
server:
  port: 8085
  servlet:
    context-path: /api/notification
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,httptrace,prometheus
app:
  home:
    #logs: /Users/${USER}/Logs
    logs: /Users/Logs
#Eureka-Config:
app.eureka.service.host: localhost
app.eureka.service.port: 801
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka.service.host}:${app.eureka.service.port}/eureka

#Service-config
app.eureka.api.gateway.port: 80

#User-service
user.service.url: http://USER-PROFILE/api/user/profile
user.service.getAllUsersEligibleForTraining: /userProfile/getAllUsersEligibleForTraining?paramDate=