spring:
  application:
    name: user-profile
  main:
    banner-mode: "off"
    allow-circular-references: true
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: "none"


#bezkoder:
#  app:
#    jwtSecret: "bezKoderSecretKey"
#    jwtExpirationMs: 86400000
server:
  port: 8084
  servlet:
    context-path: /api/user/profile
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,httptrace,prometheus
app:
  home:
    #logs: /Users/${USER}/Logs
    logs: /Users/Logs
  god:
    user:
      username: my.app.domain@app.com
      password: AdMiN!3#1$#
      mobile: +8801712645571
      role: GOD_ADMIN
      policy: god_admin_policy
      action: Write
      resource: /api/**
  login:
    token:
      ttl:
        duration:
          millis: 3600000

#Eureka-Config:
app.eureka.service.host: localhost
app.eureka.service.port: 801
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka.service.host}:${app.eureka.service.port}/eureka
#    registerWithEureka: true
#    fetchRegistry: true
#  instance:
#    preferIpAddress: true

#Service-config
app.eureka.api.gateway.port: 80

#Auth-service
auth.service.url: http://AUTH-SERVICE/api/auth
#auth.service.user.by.userId: ${auth.service.url}/auth/v1/userByUserId?userId=
auth.service.user.by.userId: /auth/v1/userByUserId?userId=

#Training-Management-Service
training.management.service.url: http://TRAINING-MANAGEMENT/api/training/management
#training.management.geog.by.geogId: ${training.management.service.url}/common/getGeogByGeogId?geogId=
#training.management.dzongkhag.by.dzongkhayId: ${training.management.service.url}/common/getDzongkhagByDzongkhagId?dzongkhagId=
training.management.geog.by.geogId: /common/getGeogByGeogId?geogId=
training.management.dzongkhag.by.dzongkhayId: /common/getDzongkhagByDzongkhagId?dzongkhagId=
