spring:
  application:
    name: user-profile
  main:
    banner-mode: "off"
    allow-circular-references: true
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: "none"


#bezkoder:
#  app:
#    jwtSecret: "bezKoderSecretKey"
#    jwtExpirationMs: 86400000
server:
  port: 8084
  servlet:
    context-path: /api/user/profile
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,httptrace,prometheus
app:
  home:
    #logs: /Users/${USER}/Logs
    logs: /Users/Logs
  god:
    user:
      username: my.app.domain@app.com
      password: AdMiN!3#1$#
      mobile: +8801712645571
      role: GOD_ADMIN
      policy: god_admin_policy
      action: Write
      resource: /api/**
  login:
    token:
      ttl:
        duration:
          millis: 3600000

#Eureka-Config:
app.eureka.service.host: localhost
app.eureka.service.port: 801
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka.service.host}:${app.eureka.service.port}/eureka
    fetch-registry: true

#Service-config
app.eureka.api.gateway.port: 80
app.eureka.auth.service.url: http://${app.eureka.service.host}:${app.eureka.api.gateway.port}/AUTH-SERVICE/api/auth/

