spring:
  application:
    name: api-gateway
  main:
    banner-mode: off
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - origin
              - content-type
              - accept
              - authorization
              - X-Auth-Token
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
            maxAge: 1209600
            allowCredentials: false
        add-to-simple-url-handler-mapping: true
server:
  port: 80
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,httptrace,prometheus,gateway
#Spring-Redis-Config:
redis:
  host: localhost
  port: 6379
#Eureka-Config:
app.eureka.service.host: localhost
app.eureka.service.port: 801
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka.service.host}:${app.eureka.service.port}/eureka