spring:
  application:
    name: medical-screening
  main:
    banner-mode: "off"
server:
  port: 8088
  servlet:
    context-path: /api/medical/screening
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,httptrace,prometheus
app:
  home:
    #logs: /Users/${USER}/Logs
    logs: /Users/Logs
#Eureka-Config:
app.eureka.service.host: localhost
app.eureka.service.port: 801
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka.service.host}:${app.eureka.service.port}/eureka
#    registerWithEureka: true
#    fetchRegistry: true
#  instance:
#    preferIpAddress: true

#Service-config
app.eureka.api.gateway.port: 80

#User-service
user.service.url: http://USER-PROFILE/api/user/profile
user.service.profile.by.userId: /userProfile/getProfileInfo?userId=

#Training-Management-Service
training.management.service.url: http://TRAINING-MANAGEMENT/api/training/management
training.management.hospital.by.hospitalId: /common/getHospitalById?hospitalId=
training.management.mappedHospital.by.hospitalId: /common/getHospitalMappingByHospitalId?hospitalId=
training.management.hospital.by.hospitalName: /common/getHospitalByName?hospitalName=
