spring:
  application:
    name: enrolment-deferment-exemption
  main:
    banner-mode: "off"
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: "none"
      hibernate:
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
server:
  port: 8087
  servlet:
    context-path: /api/enrolment/deferment/exemption
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,httptrace,prometheus
logging:
  level:
    org:
      hibernate:
        SQL: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: true
app:
  home:
    #logs: /Users/${USER}/Logs
    logs: /Users/Logs
#Eureka-Config:
app.eureka.service.host: localhost
app.eureka.service.port: 801

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka.service.host}:${app.eureka.service.port}/eureka
#    registerWithEureka: true
#    fetchRegistry: true
#  instance:
#    preferIpAddress: true

#Service-config
app.eureka.api.gateway.port: 80

#User-service
user.service.url: http://USER-PROFILE/api/user/profile
user.service.check.under.age: /userProfile/checkUnderAge?userId=
user.service.profile.by.userId: /userProfile/getProfileInfo?userId=
user.service.profile.by.userIds: /userProfile/getProfileInfoByIds?userIds=
user.service.profile.by.partial.cid: /userProfile/getUserInformationByPartialCid?cid=
user.service.operator: /saUser/getOperatorUsers



#Training-Management-Service
training.management.service.url: http://TRAINING-MANAGEMENT/api/training/management
training.management.academy.by.academyId: /common/getTrainingAcademyById?academyId=
training.management.academy.allAcademy: /common/getAllTrainingAcademies
training.management.course.by.courseId: /fieldSpecializations/getCourseByCourseId?courseId=
training.management.hospital.by.hospitalId: /common/getHospitalById?hospitalId=
training.management.mappedHospital.by.hospitalId: /common/getHospitalMappingByHospitalId?hospitalId=
training.management.trainingCapacitites.by.trainingId: /trainingAcademyCapacities/getAllTrainingAcaCapByAcademyId?year=
training.management.changeAllocateCapacities: /trainingAcademyCapacities/changeAllocateCapacities
training.management.trainingAcademyCapacities: /trainingAcademyCapacities
